- hosts: all
  become: yes
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: yes    
    when: ansible_facts['nodename'] == "ip-172-31-19-252"
                    